version: '2'
services:

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7.3
    volumes:
      - ./data-rabbitmq-prod:/var/lib/rabbitmq   #for data persistence
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  ui:
    #NOTE: we use same image than celery worker because we need worker tasks to be registered with flower
    #, now we use flower api to submit jobs
    image: 10.8.0.1:5500/ci-celery
    command: flower -A worker --port=5555 --persistent=True --db=/db/db --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
    environment:
      - BROKER=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
    volumes:
      - ./data-flower-prod:/db  #for data persistence
    ports:
        - "80:5555"
    links:
        - rabbit
    depends_on:
        - rabbit
